
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author User
 */
public class patronPanel extends javax.swing.JPanel {

    /**
     * Creates new form patronPanel
     */
    public patronPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        btnVeiw = new javax.swing.JButton();
        btnIssue = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        contentBookPanel = new javax.swing.JPanel();
        veiwPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JButton();
        issuePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIssuePatron = new javax.swing.JButton();
        returnPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReturnPatron = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        menuPanel.setLayout(new java.awt.GridLayout(3, 1));

        btnVeiw.setBackground(new java.awt.Color(255, 255, 204));
        btnVeiw.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnVeiw.setText("Veiw Book");
        btnVeiw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiwActionPerformed(evt);
            }
        });
        menuPanel.add(btnVeiw);

        btnIssue.setBackground(new java.awt.Color(255, 255, 204));
        btnIssue.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnIssue.setText("Issue Book");
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        menuPanel.add(btnIssue);

        btnReturn.setBackground(new java.awt.Color(255, 255, 204));
        btnReturn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnReturn.setText("Return Book");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        menuPanel.add(btnReturn);

        contentBookPanel.setLayout(new java.awt.CardLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnSearchBook.setBackground(new java.awt.Color(255, 255, 204));
        btnSearchBook.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSearchBook.setText("Search");

        javax.swing.GroupLayout veiwPanelLayout = new javax.swing.GroupLayout(veiwPanel);
        veiwPanel.setLayout(veiwPanelLayout);
        veiwPanelLayout.setHorizontalGroup(
            veiwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiwPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(veiwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(veiwPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        veiwPanelLayout.setVerticalGroup(
            veiwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiwPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(veiwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, veiwPanelLayout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(btnSearchBook)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        contentBookPanel.add(veiwPanel, "card2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIssuePatron.setBackground(new java.awt.Color(255, 255, 204));
        btnIssuePatron.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnIssuePatron.setText("Issue");
        btnIssuePatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssuePatronActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issuePanelLayout = new javax.swing.GroupLayout(issuePanel);
        issuePanel.setLayout(issuePanelLayout);
        issuePanelLayout.setHorizontalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnIssuePatron, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        issuePanelLayout.setVerticalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIssuePatron)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        contentBookPanel.add(issuePanel, "card3");

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReturnPatron.setBackground(new java.awt.Color(255, 255, 204));
        btnReturnPatron.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnReturnPatron.setText("Return");
        btnReturnPatron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReturnPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnPatronActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Book ID");

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnReturnPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReturnPatron)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        contentBookPanel.add(returnPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 293, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(contentBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(contentBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnVeiwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiwActionPerformed
       CardLayout c = (CardLayout) contentBookPanel.getLayout();
         c.show(contentBookPanel, "card2" );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVeiwActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
     CardLayout c = (CardLayout) contentBookPanel.getLayout();
         c.show(contentBookPanel, "card3" );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssueActionPerformed

    private void btnIssuePatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssuePatronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssuePatronActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
     CardLayout c = (CardLayout) contentBookPanel.getLayout();
         c.show(contentBookPanel, "card4" );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnReturnPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnPatronActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnPatronActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnIssuePatron;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturnPatron;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnVeiw;
    private javax.swing.JPanel contentBookPanel;
    private javax.swing.JPanel issuePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel veiwPanel;
    // End of variables declaration//GEN-END:variables
}
